version: "3.8"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hackathon-network

  backend:
    image: ghcr.io/rattrapage-hackathon-m1/authentification:v1.1.1
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - postgres
    networks:
      - hackathon-network

  nginx:
    image: nginx:1.25.5-alpine-slim
    ports:
      - 8000:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - hackathon-network

networks:
  hackathon-network:

volumes:
  postgres-data:
