version: "3.8"
services:
  postgres_auth:
    container_name: postgres_auth
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  auth:
    image: ghcr.io/rattrapage-hackathon-m1/authentification:v1.1.8
    ports:
      - 8001:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_auth:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    depends_on:
      - postgres_auth
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  postgres_crud:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: crud
    ports:
      - 5433:5432

  api-crud:
    image: ghcr.io/rattrapage-hackathon-m1/api-crud:v1.3.0
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_crud:5432/crud
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    depends_on:
      - postgres_crud

  nginx:
    image: nginx:1.25.5-alpine-slim
    ports:
      - 8000:80
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"

  front:
    image: ghcr.io/rattrapage-hackathon-m1/frontend:v0.0.1
    ports:
      - "5173:5173"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
